add necessary docs for issue 48
lambdaisland/kaocha-cljs pull request #54
Opened 2023-04-14 09:23 UTC by humorless

add necessary documentation for #48

2023-04-14 18:45 UTC, alysbrooks requested changes
Thanks for adding this! I Just fixed some minor issues.

It might be nice to go into the tradeoffs between a browser REPL versus including a DOM. I'm not sure whether there are any downsides to `global-jsdom`, but I suspect it has some differences from a browser DOM. The pro would be avoiding the unreliability of connecting to a browser, however.

2023-04-14 18:45 UTC, alysbrooks commented on README.md
> +This usually means you're using libraries that expect a DOM (i.e. they expect to
```suggestion
This usually means you're using libraries that expect a DOM (i.e., they expect to 
```

2023-04-14 18:45 UTC, alysbrooks commented on README.md
> +find`js/document`), but you are using them in an environment where there is no DOM,
```suggestion
find `js/document`), but you are using them in an environment where there is no DOM,
```

2023-04-14 18:45 UTC, alysbrooks commented on README.md
> +2. Prepare a dom for Node environment. For example, `(js/require "global-jsdom")`
```suggestion
2. Prepare a DOM for Node environment. For example, `(js/require "global-jsdom")` 
```

2023-04-15 07:40 UTC, humorless commented
> Thanks for adding this! I Just fixed some minor issues.
> 
> It might be nice to go into the tradeoffs between a browser REPL versus including a DOM. I'm not sure whether there are any downsides to `global-jsdom`, but I suspect it has some differences from a browser DOM. The pro would be avoiding the unreliability of connecting to a browser, however.

I got the idea/information of the `global-jsdom` thing by googling, and I found Arne's reply on ClojureVerse discussions. I think it would be nice to also add this method.

2023-04-15 11:11 UTC, merged